// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yoga.Api.Data;

#nullable disable

namespace Yoga.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411144913_AddDraftWorkflow")]
    partial class AddDraftWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Yoga.Shared.Models.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Yoga.Shared.Models.Consultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDraft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOffline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("Yoga.Shared.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDraft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOffline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Yoga.Shared.Models.CourseLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseModuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseModuleId");

                    b.ToTable("CourseLessons");
                });

            modelBuilder.Entity("Yoga.Shared.Models.CourseModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseModules");
                });

            modelBuilder.Entity("Yoga.Shared.Models.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactDetails")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Messager")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OperatorNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("RetreatId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("YagyaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("Yoga.Shared.Models.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StoragePath")
                        .IsUnique();

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("Yoga.Shared.Models.Retreat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EventEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EventStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDraft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Retreats");
                });

            modelBuilder.Entity("Yoga.Shared.Models.RetreatSubcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RetreatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RetreatId");

                    b.ToTable("RetreatSubcategories");
                });

            modelBuilder.Entity("Yoga.Shared.Models.SitePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDraft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("SitePages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            IsActive = true,
                            IsDraft = false,
                            Slug = "about"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            IsActive = true,
                            IsDraft = false,
                            Slug = "contacts"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444403"),
                            IsActive = true,
                            IsDraft = false,
                            Slug = "home"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444404"),
                            IsActive = true,
                            IsDraft = false,
                            Slug = "courses"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444405"),
                            IsActive = true,
                            IsDraft = false,
                            Slug = "consultations"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444406"),
                            IsActive = true,
                            IsDraft = false,
                            Slug = "retreats"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444407"),
                            IsActive = true,
                            IsDraft = false,
                            Slug = "yagyas"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444408"),
                            IsActive = true,
                            IsDraft = false,
                            Slug = "blog"
                        });
                });

            modelBuilder.Entity("Yoga.Shared.Models.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "Field", "Language")
                        .IsUnique();

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000001"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "MetaTitle",
                            Language = "ru",
                            Value = "Ретриты | shakti.ashram"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000002"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "MetaTitle",
                            Language = "en",
                            Value = "Retreats | shakti.ashram"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000003"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "MetaTitle",
                            Language = "uk",
                            Value = "Ретрити | shakti.ashram"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000004"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "HeroTitle",
                            Language = "ru",
                            Value = "Ретриты"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000005"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "HeroTitle",
                            Language = "en",
                            Value = "Retreats"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000006"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "HeroTitle",
                            Language = "uk",
                            Value = "Ретрити"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000007"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "HeroSubtitle",
                            Language = "ru",
                            Value = "Погружение в практику вне суеты повседневности."
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000008"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "HeroSubtitle",
                            Language = "en",
                            Value = "Immersion in practice away from everyday rush."
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000009"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "HeroSubtitle",
                            Language = "uk",
                            Value = "Занурення в практику поза метушнею буднів."
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000010"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "HeroImageUrl",
                            Language = "ru",
                            Value = "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1600&q=80"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000011"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "HeroImageUrl",
                            Language = "en",
                            Value = "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1600&q=80"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000012"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "HeroImageUrl",
                            Language = "uk",
                            Value = "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1600&q=80"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000013"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "Content",
                            Language = "ru",
                            Value = "<p>Здесь появятся анонсы ретритов и подробности программ. Чтобы узнать о ближайших датах, <a href=\"/contacts\">свяжитесь с нами</a>.</p>"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000014"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "Content",
                            Language = "en",
                            Value = "<p>Retreat announcements and programme details will appear here. To ask about upcoming dates, <a href=\"/contacts\">contact us</a>.</p>"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000015"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444406"),
                            EntityType = "SitePage",
                            Field = "Content",
                            Language = "uk",
                            Value = "<p>Тут з’являться анонси ретритів і деталі програм. Щоб дізнатися про найближчі дати, <a href=\"/contacts\">напишіть нам</a>.</p>"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000016"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "MetaTitle",
                            Language = "ru",
                            Value = "Ягьи | shakti.ashram"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000017"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "MetaTitle",
                            Language = "en",
                            Value = "Yagyas | shakti.ashram"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000018"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "MetaTitle",
                            Language = "uk",
                            Value = "Ягʼї | shakti.ashram"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000019"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "HeroTitle",
                            Language = "ru",
                            Value = "Ягьи"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000020"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "HeroTitle",
                            Language = "en",
                            Value = "Yagyas"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000021"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "HeroTitle",
                            Language = "uk",
                            Value = "Ягʼї"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000022"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "HeroSubtitle",
                            Language = "ru",
                            Value = "Совместные ритуалы и практики для общего намерения."
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000023"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "HeroSubtitle",
                            Language = "en",
                            Value = "Group rituals and practices for a shared intention."
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000024"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "HeroSubtitle",
                            Language = "uk",
                            Value = "Спільні ритуали та практики для спільного наміру."
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000025"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "HeroImageUrl",
                            Language = "ru",
                            Value = "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1600&q=80"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000026"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "HeroImageUrl",
                            Language = "en",
                            Value = "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1600&q=80"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000027"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "HeroImageUrl",
                            Language = "uk",
                            Value = "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1600&q=80"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000028"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "Content",
                            Language = "ru",
                            Value = "<p>Расписание и описание ягьев будет публиковаться на этой странице. По вопросам участия напишите через <a href=\"/contacts\">контакты</a>.</p>"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000029"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "Content",
                            Language = "en",
                            Value = "<p>Schedules and descriptions of yagyas will be published here. For participation questions, use our <a href=\"/contacts\">contacts page</a>.</p>"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000030"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444407"),
                            EntityType = "SitePage",
                            Field = "Content",
                            Language = "uk",
                            Value = "<p>Розклад і опис ягʼїв публікуватимуться тут. З питань участі звертайтеся через <a href=\"/contacts\">контакти</a>.</p>"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000031"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "MetaTitle",
                            Language = "ru",
                            Value = "Блог | shakti.ashram"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000032"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "MetaTitle",
                            Language = "en",
                            Value = "Blog | shakti.ashram"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000033"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "MetaTitle",
                            Language = "uk",
                            Value = "Блог | shakti.ashram"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000034"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "HeroTitle",
                            Language = "ru",
                            Value = "Блог"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000035"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "HeroTitle",
                            Language = "en",
                            Value = "Blog"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000036"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "HeroTitle",
                            Language = "uk",
                            Value = "Блог"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000037"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "HeroSubtitle",
                            Language = "ru",
                            Value = "Статьи, заметки и материалы для практики."
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000038"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "HeroSubtitle",
                            Language = "en",
                            Value = "Articles, notes and materials for practice."
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000039"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "HeroSubtitle",
                            Language = "uk",
                            Value = "Статті, нотатки та матеріали для практики."
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000040"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "HeroImageUrl",
                            Language = "ru",
                            Value = "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1600&q=80"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000041"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "HeroImageUrl",
                            Language = "en",
                            Value = "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1600&q=80"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000042"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "HeroImageUrl",
                            Language = "uk",
                            Value = "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1600&q=80"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000043"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "Content",
                            Language = "ru",
                            Value = "<p>Публикации блога появятся здесь. Подпишитесь на наши каналы в <a href=\"/contacts\">соцсетях</a>, чтобы не пропустить выход материалов.</p>"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000044"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "Content",
                            Language = "en",
                            Value = "<p>Blog posts will appear here. Follow our channels via <a href=\"/contacts\">contacts</a> so you do not miss new materials.</p>"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-000000000045"),
                            EntityId = new Guid("44444444-4444-4444-4444-444444444408"),
                            EntityType = "SitePage",
                            Field = "Content",
                            Language = "uk",
                            Value = "<p>Публікації блогу з’являтимуться тут. Слідкуйте за нашими каналами у <a href=\"/contacts\">соцмережах</a>, щоб не пропустити матеріали.</p>"
                        });
                });

            modelBuilder.Entity("Yoga.Shared.Models.UiTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Language")
                        .IsUnique();

                    b.ToTable("UiTranslations");
                });

            modelBuilder.Entity("Yoga.Shared.Models.Yagya", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EventEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EventStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDraft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Yagyas");
                });

            modelBuilder.Entity("Yoga.Shared.Models.YagyaSubcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("YagyaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("YagyaId");

                    b.ToTable("YagyaSubcategories");
                });

            modelBuilder.Entity("Yoga.Shared.Models.CourseLesson", b =>
                {
                    b.HasOne("Yoga.Shared.Models.CourseModule", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Yoga.Shared.Models.CourseModule", b =>
                {
                    b.HasOne("Yoga.Shared.Models.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Yoga.Shared.Models.RetreatSubcategory", b =>
                {
                    b.HasOne("Yoga.Shared.Models.Retreat", "Retreat")
                        .WithMany("Subcategories")
                        .HasForeignKey("RetreatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Retreat");
                });

            modelBuilder.Entity("Yoga.Shared.Models.YagyaSubcategory", b =>
                {
                    b.HasOne("Yoga.Shared.Models.Yagya", "Yagya")
                        .WithMany("Subcategories")
                        .HasForeignKey("YagyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yagya");
                });

            modelBuilder.Entity("Yoga.Shared.Models.Course", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Yoga.Shared.Models.CourseModule", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Yoga.Shared.Models.Retreat", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("Yoga.Shared.Models.Yagya", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
